"""fixparks

Revision ID: 09923c962b27
Revises: 9fd8ad4dc1ce
Create Date: 2023-10-08 06:18:31.089320

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '09923c962b27'
down_revision = '9fd8ad4dc1ce'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reviews', schema=None) as batch_op:
        batch_op.add_column(sa.Column('park_id', sa.Integer(), nullable=True))
        batch_op.drop_constraint('fk_reviews_trip_id_parks', type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_reviews_park_id_parks'), 'parks', ['park_id'], ['id'])
        batch_op.drop_column('trip_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reviews', schema=None) as batch_op:
        batch_op.add_column(sa.Column('trip_id', sa.INTEGER(), nullable=True))
        batch_op.drop_constraint(batch_op.f('fk_reviews_park_id_parks'), type_='foreignkey')
        batch_op.create_foreign_key('fk_reviews_trip_id_parks', 'parks', ['trip_id'], ['id'])
        batch_op.drop_column('park_id')

    # ### end Alembic commands ###
