"""change

Revision ID: 25671e247577
Revises: 09923c962b27
Create Date: 2023-10-08 17:05:11.363709

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '25671e247577'
down_revision = '09923c962b27'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('parks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('entry_fee', sa.Integer(), nullable=True))
        batch_op.drop_column('approximate_cost')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('parks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('approximate_cost', sa.INTEGER(), nullable=True))
        batch_op.drop_column('entry_fee')

    # ### end Alembic commands ###
